//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataUpdate.JsInterfaceInspection {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://synToCity.synchrodata.daniu.com/", ConfigurationName="JsInterfaceInspection.IVehicleService")]
    public interface IVehicleService {
        
        // CODEGEN: 命名空间  的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.GetCheckListResponse GetCheckList(DataUpdate.JsInterfaceInspection.GetCheckList request);
        
        // CODEGEN: 命名空间  的元素名称 unitid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.BeginCheckResponse BeginCheck(DataUpdate.JsInterfaceInspection.BeginCheck request);
        
        // CODEGEN: 命名空间  的元素名称 vehiclexml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.vehicleloginResponse vehiclelogin(DataUpdate.JsInterfaceInspection.vehiclelogin request);
        
        // CODEGEN: 命名空间  的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.getresResponse getres(DataUpdate.JsInterfaceInspection.getres request);
        
        // CODEGEN: 命名空间  的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.UploadInspectionResultResponse UploadInspectionResult(DataUpdate.JsInterfaceInspection.UploadInspectionResult request);
        
        // CODEGEN: 命名空间  的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.GetVehicleResponse GetVehicle(DataUpdate.JsInterfaceInspection.GetVehicle request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.GetBaseTypeInfoResponse GetBaseTypeInfo(DataUpdate.JsInterfaceInspection.GetBaseTypeInfo request);
        
        // CODEGEN: 命名空间  的元素名称 unitid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.LoginServerResponse LoginServer(DataUpdate.JsInterfaceInspection.LoginServer request);
        
        // CODEGEN: 命名空间  的元素名称 res 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.validateJCResponse validateJC(DataUpdate.JsInterfaceInspection.validateJC request);
        
        // CODEGEN: 命名空间  的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceInspection.GetYCVehicleResponse GetYCVehicle(DataUpdate.JsInterfaceInspection.GetYCVehicle request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCheckList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCheckList", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetCheckListBody Body;
        
        public GetCheckList() {
        }
        
        public GetCheckList(DataUpdate.JsInterfaceInspection.GetCheckListBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCheckListBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string unitid;
        
        public GetCheckListBody() {
        }
        
        public GetCheckListBody(string token, string unitid) {
            this.token = token;
            this.unitid = unitid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCheckListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCheckListResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetCheckListResponseBody Body;
        
        public GetCheckListResponse() {
        }
        
        public GetCheckListResponse(DataUpdate.JsInterfaceInspection.GetCheckListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCheckListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetCheckListResponseBody() {
        }
        
        public GetCheckListResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BeginCheck {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BeginCheck", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.BeginCheckBody Body;
        
        public BeginCheck() {
        }
        
        public BeginCheck(DataUpdate.JsInterfaceInspection.BeginCheckBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class BeginCheckBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string unitid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lineid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string plate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string qwg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string hwg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string hcl;
        
        public BeginCheckBody() {
        }
        
        public BeginCheckBody(string unitid, string lineid, string plate, string vin, string qwg, string hwg, string hcl) {
            this.unitid = unitid;
            this.lineid = lineid;
            this.plate = plate;
            this.vin = vin;
            this.qwg = qwg;
            this.hwg = hwg;
            this.hcl = hcl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BeginCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BeginCheckResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.BeginCheckResponseBody Body;
        
        public BeginCheckResponse() {
        }
        
        public BeginCheckResponse(DataUpdate.JsInterfaceInspection.BeginCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class BeginCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public BeginCheckResponseBody() {
        }
        
        public BeginCheckResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vehiclelogin {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vehiclelogin", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.vehicleloginBody Body;
        
        public vehiclelogin() {
        }
        
        public vehiclelogin(DataUpdate.JsInterfaceInspection.vehicleloginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class vehicleloginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vehiclexml;
        
        public vehicleloginBody() {
        }
        
        public vehicleloginBody(string vehiclexml) {
            this.vehiclexml = vehiclexml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vehicleloginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vehicleloginResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.vehicleloginResponseBody Body;
        
        public vehicleloginResponse() {
        }
        
        public vehicleloginResponse(DataUpdate.JsInterfaceInspection.vehicleloginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class vehicleloginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public vehicleloginResponseBody() {
        }
        
        public vehicleloginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getres {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getres", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.getresBody Body;
        
        public getres() {
        }
        
        public getres(DataUpdate.JsInterfaceInspection.getresBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getresBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string unitid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int checkmethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int hasover;
        
        public getresBody() {
        }
        
        public getresBody(string token, string unitid, int checkmethod, int hasover) {
            this.token = token;
            this.unitid = unitid;
            this.checkmethod = checkmethod;
            this.hasover = hasover;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getresResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.getresResponseBody Body;
        
        public getresResponse() {
        }
        
        public getresResponse(DataUpdate.JsInterfaceInspection.getresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getresResponseBody() {
        }
        
        public getresResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadInspectionResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadInspectionResult", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.UploadInspectionResultBody Body;
        
        public UploadInspectionResult() {
        }
        
        public UploadInspectionResult(DataUpdate.JsInterfaceInspection.UploadInspectionResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class UploadInspectionResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string unitid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string checkresult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int checkmethod;
        
        public UploadInspectionResultBody() {
        }
        
        public UploadInspectionResultBody(string token, string unitid, string checkresult, int checkmethod) {
            this.token = token;
            this.unitid = unitid;
            this.checkresult = checkresult;
            this.checkmethod = checkmethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadInspectionResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadInspectionResultResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.UploadInspectionResultResponseBody Body;
        
        public UploadInspectionResultResponse() {
        }
        
        public UploadInspectionResultResponse(DataUpdate.JsInterfaceInspection.UploadInspectionResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class UploadInspectionResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public UploadInspectionResultResponseBody() {
        }
        
        public UploadInspectionResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehicle {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehicle", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetVehicleBody Body;
        
        public GetVehicle() {
        }
        
        public GetVehicle(DataUpdate.JsInterfaceInspection.GetVehicleBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetVehicleBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string unitid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vin;
        
        public GetVehicleBody() {
        }
        
        public GetVehicleBody(string token, string unitid, string vin) {
            this.token = token;
            this.unitid = unitid;
            this.vin = vin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehicleResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetVehicleResponseBody Body;
        
        public GetVehicleResponse() {
        }
        
        public GetVehicleResponse(DataUpdate.JsInterfaceInspection.GetVehicleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetVehicleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetVehicleResponseBody() {
        }
        
        public GetVehicleResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBaseTypeInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBaseTypeInfo", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetBaseTypeInfoBody Body;
        
        public GetBaseTypeInfo() {
        }
        
        public GetBaseTypeInfo(DataUpdate.JsInterfaceInspection.GetBaseTypeInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBaseTypeInfoBody {
        
        public GetBaseTypeInfoBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBaseTypeInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBaseTypeInfoResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetBaseTypeInfoResponseBody Body;
        
        public GetBaseTypeInfoResponse() {
        }
        
        public GetBaseTypeInfoResponse(DataUpdate.JsInterfaceInspection.GetBaseTypeInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetBaseTypeInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetBaseTypeInfoResponseBody() {
        }
        
        public GetBaseTypeInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginServer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginServer", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.LoginServerBody Body;
        
        public LoginServer() {
        }
        
        public LoginServer(DataUpdate.JsInterfaceInspection.LoginServerBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginServerBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string unitid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lineid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pwd;
        
        public LoginServerBody() {
        }
        
        public LoginServerBody(string unitid, string lineid, string username, string pwd) {
            this.unitid = unitid;
            this.lineid = lineid;
            this.username = username;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginServerResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.LoginServerResponseBody Body;
        
        public LoginServerResponse() {
        }
        
        public LoginServerResponse(DataUpdate.JsInterfaceInspection.LoginServerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginServerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public LoginServerResponseBody() {
        }
        
        public LoginServerResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateJC {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateJC", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.validateJCBody Body;
        
        public validateJC() {
        }
        
        public validateJC(DataUpdate.JsInterfaceInspection.validateJCBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateJCBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string res;
        
        public validateJCBody() {
        }
        
        public validateJCBody(string res) {
            this.res = res;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateJCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateJCResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.validateJCResponseBody Body;
        
        public validateJCResponse() {
        }
        
        public validateJCResponse(DataUpdate.JsInterfaceInspection.validateJCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validateJCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validateJCResponseBody() {
        }
        
        public validateJCResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetYCVehicle {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetYCVehicle", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetYCVehicleBody Body;
        
        public GetYCVehicle() {
        }
        
        public GetYCVehicle(DataUpdate.JsInterfaceInspection.GetYCVehicleBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetYCVehicleBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string plate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string color;
        
        public GetYCVehicleBody() {
        }
        
        public GetYCVehicleBody(string token, string plate, string color) {
            this.token = token;
            this.plate = plate;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetYCVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetYCVehicleResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceInspection.GetYCVehicleResponseBody Body;
        
        public GetYCVehicleResponse() {
        }
        
        public GetYCVehicleResponse(DataUpdate.JsInterfaceInspection.GetYCVehicleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetYCVehicleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetYCVehicleResponseBody() {
        }
        
        public GetYCVehicleResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehicleServiceChannel : DataUpdate.JsInterfaceInspection.IVehicleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<DataUpdate.JsInterfaceInspection.IVehicleService>, DataUpdate.JsInterfaceInspection.IVehicleService {
        
        public VehicleServiceClient() {
        }
        
        public VehicleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.GetCheckListResponse DataUpdate.JsInterfaceInspection.IVehicleService.GetCheckList(DataUpdate.JsInterfaceInspection.GetCheckList request) {
            return base.Channel.GetCheckList(request);
        }
        
        public string GetCheckList(string token, string unitid) {
            DataUpdate.JsInterfaceInspection.GetCheckList inValue = new DataUpdate.JsInterfaceInspection.GetCheckList();
            inValue.Body = new DataUpdate.JsInterfaceInspection.GetCheckListBody();
            inValue.Body.token = token;
            inValue.Body.unitid = unitid;
            DataUpdate.JsInterfaceInspection.GetCheckListResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).GetCheckList(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.BeginCheckResponse DataUpdate.JsInterfaceInspection.IVehicleService.BeginCheck(DataUpdate.JsInterfaceInspection.BeginCheck request) {
            return base.Channel.BeginCheck(request);
        }
        
        public string BeginCheck(string unitid, string lineid, string plate, string vin, string qwg, string hwg, string hcl) {
            DataUpdate.JsInterfaceInspection.BeginCheck inValue = new DataUpdate.JsInterfaceInspection.BeginCheck();
            inValue.Body = new DataUpdate.JsInterfaceInspection.BeginCheckBody();
            inValue.Body.unitid = unitid;
            inValue.Body.lineid = lineid;
            inValue.Body.plate = plate;
            inValue.Body.vin = vin;
            inValue.Body.qwg = qwg;
            inValue.Body.hwg = hwg;
            inValue.Body.hcl = hcl;
            DataUpdate.JsInterfaceInspection.BeginCheckResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).BeginCheck(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.vehicleloginResponse DataUpdate.JsInterfaceInspection.IVehicleService.vehiclelogin(DataUpdate.JsInterfaceInspection.vehiclelogin request) {
            return base.Channel.vehiclelogin(request);
        }
        
        public string vehiclelogin(string vehiclexml) {
            DataUpdate.JsInterfaceInspection.vehiclelogin inValue = new DataUpdate.JsInterfaceInspection.vehiclelogin();
            inValue.Body = new DataUpdate.JsInterfaceInspection.vehicleloginBody();
            inValue.Body.vehiclexml = vehiclexml;
            DataUpdate.JsInterfaceInspection.vehicleloginResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).vehiclelogin(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.getresResponse DataUpdate.JsInterfaceInspection.IVehicleService.getres(DataUpdate.JsInterfaceInspection.getres request) {
            return base.Channel.getres(request);
        }
        
        public string getres(string token, string unitid, int checkmethod, int hasover) {
            DataUpdate.JsInterfaceInspection.getres inValue = new DataUpdate.JsInterfaceInspection.getres();
            inValue.Body = new DataUpdate.JsInterfaceInspection.getresBody();
            inValue.Body.token = token;
            inValue.Body.unitid = unitid;
            inValue.Body.checkmethod = checkmethod;
            inValue.Body.hasover = hasover;
            DataUpdate.JsInterfaceInspection.getresResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).getres(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.UploadInspectionResultResponse DataUpdate.JsInterfaceInspection.IVehicleService.UploadInspectionResult(DataUpdate.JsInterfaceInspection.UploadInspectionResult request) {
            return base.Channel.UploadInspectionResult(request);
        }
        
        public string UploadInspectionResult(string token, string unitid, string checkresult, int checkmethod) {
            DataUpdate.JsInterfaceInspection.UploadInspectionResult inValue = new DataUpdate.JsInterfaceInspection.UploadInspectionResult();
            inValue.Body = new DataUpdate.JsInterfaceInspection.UploadInspectionResultBody();
            inValue.Body.token = token;
            inValue.Body.unitid = unitid;
            inValue.Body.checkresult = checkresult;
            inValue.Body.checkmethod = checkmethod;
            DataUpdate.JsInterfaceInspection.UploadInspectionResultResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).UploadInspectionResult(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.GetVehicleResponse DataUpdate.JsInterfaceInspection.IVehicleService.GetVehicle(DataUpdate.JsInterfaceInspection.GetVehicle request) {
            return base.Channel.GetVehicle(request);
        }
        
        public string GetVehicle(string token, string unitid, string vin) {
            DataUpdate.JsInterfaceInspection.GetVehicle inValue = new DataUpdate.JsInterfaceInspection.GetVehicle();
            inValue.Body = new DataUpdate.JsInterfaceInspection.GetVehicleBody();
            inValue.Body.token = token;
            inValue.Body.unitid = unitid;
            inValue.Body.vin = vin;
            DataUpdate.JsInterfaceInspection.GetVehicleResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).GetVehicle(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.GetBaseTypeInfoResponse DataUpdate.JsInterfaceInspection.IVehicleService.GetBaseTypeInfo(DataUpdate.JsInterfaceInspection.GetBaseTypeInfo request) {
            return base.Channel.GetBaseTypeInfo(request);
        }
        
        public string GetBaseTypeInfo() {
            DataUpdate.JsInterfaceInspection.GetBaseTypeInfo inValue = new DataUpdate.JsInterfaceInspection.GetBaseTypeInfo();
            inValue.Body = new DataUpdate.JsInterfaceInspection.GetBaseTypeInfoBody();
            DataUpdate.JsInterfaceInspection.GetBaseTypeInfoResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).GetBaseTypeInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.LoginServerResponse DataUpdate.JsInterfaceInspection.IVehicleService.LoginServer(DataUpdate.JsInterfaceInspection.LoginServer request) {
            return base.Channel.LoginServer(request);
        }
        
        public string LoginServer(string unitid, string lineid, string username, string pwd) {
            DataUpdate.JsInterfaceInspection.LoginServer inValue = new DataUpdate.JsInterfaceInspection.LoginServer();
            inValue.Body = new DataUpdate.JsInterfaceInspection.LoginServerBody();
            inValue.Body.unitid = unitid;
            inValue.Body.lineid = lineid;
            inValue.Body.username = username;
            inValue.Body.pwd = pwd;
            DataUpdate.JsInterfaceInspection.LoginServerResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).LoginServer(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.validateJCResponse DataUpdate.JsInterfaceInspection.IVehicleService.validateJC(DataUpdate.JsInterfaceInspection.validateJC request) {
            return base.Channel.validateJC(request);
        }
        
        public string validateJC(string res) {
            DataUpdate.JsInterfaceInspection.validateJC inValue = new DataUpdate.JsInterfaceInspection.validateJC();
            inValue.Body = new DataUpdate.JsInterfaceInspection.validateJCBody();
            inValue.Body.res = res;
            DataUpdate.JsInterfaceInspection.validateJCResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).validateJC(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceInspection.GetYCVehicleResponse DataUpdate.JsInterfaceInspection.IVehicleService.GetYCVehicle(DataUpdate.JsInterfaceInspection.GetYCVehicle request) {
            return base.Channel.GetYCVehicle(request);
        }
        
        public string GetYCVehicle(string token, string plate, string color) {
            DataUpdate.JsInterfaceInspection.GetYCVehicle inValue = new DataUpdate.JsInterfaceInspection.GetYCVehicle();
            inValue.Body = new DataUpdate.JsInterfaceInspection.GetYCVehicleBody();
            inValue.Body.token = token;
            inValue.Body.plate = plate;
            inValue.Body.color = color;
            DataUpdate.JsInterfaceInspection.GetYCVehicleResponse retVal = ((DataUpdate.JsInterfaceInspection.IVehicleService)(this)).GetYCVehicle(inValue);
            return retVal.Body.@return;
        }
    }
}
