//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataUpdate.JsInterfaceBd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://synToCity.synchrodata.daniu.com/", ConfigurationName="JsInterfaceBd.IBdService")]
    public interface IBdService {
        
        // CODEGEN: 命名空间  的元素名称 checkresult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataUpdate.JsInterfaceBd.UploadBDResultResponse UploadBDResult(DataUpdate.JsInterfaceBd.UploadBDResult request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadBDResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadBDResult", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceBd.UploadBDResultBody Body;
        
        public UploadBDResult() {
        }
        
        public UploadBDResult(DataUpdate.JsInterfaceBd.UploadBDResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class UploadBDResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkresult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int action;
        
        public UploadBDResultBody() {
        }
        
        public UploadBDResultBody(string checkresult, int action) {
            this.checkresult = checkresult;
            this.action = action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadBDResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadBDResultResponse", Namespace="http://synToCity.synchrodata.daniu.com/", Order=0)]
        public DataUpdate.JsInterfaceBd.UploadBDResultResponseBody Body;
        
        public UploadBDResultResponse() {
        }
        
        public UploadBDResultResponse(DataUpdate.JsInterfaceBd.UploadBDResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class UploadBDResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public UploadBDResultResponseBody() {
        }
        
        public UploadBDResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBdServiceChannel : DataUpdate.JsInterfaceBd.IBdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BdServiceClient : System.ServiceModel.ClientBase<DataUpdate.JsInterfaceBd.IBdService>, DataUpdate.JsInterfaceBd.IBdService {
        
        public BdServiceClient() {
        }
        
        public BdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataUpdate.JsInterfaceBd.UploadBDResultResponse DataUpdate.JsInterfaceBd.IBdService.UploadBDResult(DataUpdate.JsInterfaceBd.UploadBDResult request) {
            return base.Channel.UploadBDResult(request);
        }
        
        public string UploadBDResult(string checkresult, int action) {
            DataUpdate.JsInterfaceBd.UploadBDResult inValue = new DataUpdate.JsInterfaceBd.UploadBDResult();
            inValue.Body = new DataUpdate.JsInterfaceBd.UploadBDResultBody();
            inValue.Body.checkresult = checkresult;
            inValue.Body.action = action;
            DataUpdate.JsInterfaceBd.UploadBDResultResponse retVal = ((DataUpdate.JsInterfaceBd.IBdService)(this)).UploadBDResult(inValue);
            return retVal.Body.@return;
        }
    }
}
